# Generated by Django 3.1.3 on 2020-11-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desciption', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='blog/images')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
