# Generated by Django 3.1.3 on 2020-11-25 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201125_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='desciption',
            new_name='description',
        ),
    ]
